export const products = [
  {
    name: "Xiaomi SmartMi",
    img: "https://i.ibb.co/W3VjdpM/oil.jpg",
    price: 350,
    stock: 10,
  },
  {
    name: "Xiaomi Mi DSXB01RM 4L",
    img: "https://i.ibb.co/12tB3nR/detol.jpg",
    price: 250,
    stock: 10,
  },
  {
    name: "Fresh Soyabean Oil",
    img: "https://i.ibb.co/W36zcS2/bag.jpg",
    price: 380,
    stock: 10,
  },
  {
    name: "Goalini Full Cream Milk",
    img: "https://i.ibb.co/LC0ccYV/mask.jpg",
    price: 300,
    stock: 10,
  },
  {
    name: "Dettol Shower Gel",
    img: "https://i.ibb.co/CBJGtLH/milk.jpg",
    price: 470,
    stock: 10,
  },
];
export const customers = [
  {
    id: 1,
    name: "Shelli Kave",
    phone: "401-594-6232",
    email: "skave0@japanpost.jp",
    package: null,
    wallet_balance: 164,
  },
  {
    id: 2,
    name: "Gallagher Ludlow",
    phone: "782-799-4008",
    email: "gludlow1@guardian.co.uk",
    package: null,
    wallet_balance: 811,
  },
  {
    id: 3,
    name: "Agnesse Clemes",
    phone: "852-723-8147",
    email: "aclemes2@unicef.org",
    package: null,
    wallet_balance: 772,
  },
  {
    id: 4,
    name: "Carson Gonzales",
    phone: "707-586-1298",
    email: "cgonzales3@samsung.com",
    package: null,
    wallet_balance: 527,
  },
  {
    id: 5,
    name: "Jemmy Erickson",
    phone: "781-318-8500",
    email: "jerickson4@alexa.com",
    package: null,
    wallet_balance: 143,
  },
  {
    id: 6,
    name: "Norbert McGirr",
    phone: "318-803-3858",
    email: "nmcgirr5@census.gov",
    package: null,
    wallet_balance: 91,
  },
  {
    id: 7,
    name: "Barclay Town",
    phone: "335-454-5006",
    email: "btown6@sohu.com",
    package: null,
    wallet_balance: 804,
  },
  {
    id: 8,
    name: "Cord Dilke",
    phone: "412-725-7938",
    email: "cdilke7@adobe.com",
    package: null,
    wallet_balance: 975,
  },
  {
    id: 9,
    name: "Dell Behnecke",
    phone: "274-262-6403",
    email: "dbehnecke8@usda.gov",
    package: null,
    wallet_balance: 537,
  },
  {
    id: 10,
    name: "Ricardo Delia",
    phone: "964-788-2867",
    email: "rdelia9@who.int",
    package: null,
    wallet_balance: 769,
  },
  {
    id: 11,
    name: "Henri Seifenmacher",
    phone: "679-820-5693",
    email: "hseifenmachera@admin.ch",
    package: null,
    wallet_balance: 110,
  },
  {
    id: 12,
    name: "Keenan Alben",
    phone: "137-376-4408",
    email: "kalbenb@nsw.gov.au",
    package: null,
    wallet_balance: 947,
  },
  {
    id: 13,
    name: "Benji Scone",
    phone: "474-720-2521",
    email: "bsconec@artisteer.com",
    package: null,
    wallet_balance: 918,
  },
  {
    id: 14,
    name: "Genny MacDougal",
    phone: "982-200-0117",
    email: "gmacdougald@seattletimes.com",
    package: null,
    wallet_balance: 454,
  },
  {
    id: 15,
    name: "Lawrence Blinde",
    phone: "514-780-7737",
    email: "lblindee@pcworld.com",
    package: null,
    wallet_balance: 725,
  },
  {
    id: 16,
    name: "Hayyim Harrisson",
    phone: "978-861-8515",
    email: "hharrissonf@netvibes.com",
    package: null,
    wallet_balance: 248,
  },
  {
    id: 17,
    name: "Sonnie Crosfield",
    phone: "481-587-1076",
    email: "scrosfieldg@msn.com",
    package: null,
    wallet_balance: 661,
  },
  {
    id: 18,
    name: "Britta Whittle",
    phone: "411-140-7835",
    email: "bwhittleh@edublogs.org",
    package: null,
    wallet_balance: 844,
  },
  {
    id: 19,
    name: "Ingeberg Hovington",
    phone: "256-876-8071",
    email: "ihovingtoni@microsoft.com",
    package: null,
    wallet_balance: 904,
  },
  {
    id: 20,
    name: "Yalonda MacFarlane",
    phone: "497-702-1025",
    email: "ymacfarlanej@google.com.hk",
    package: null,
    wallet_balance: 616,
  },
  {
    id: 21,
    name: "Cullen Ashfold",
    phone: "137-667-5634",
    email: "cashfoldk@cnbc.com",
    package: null,
    wallet_balance: 17,
  },
  {
    id: 22,
    name: "Arnie Pedlow",
    phone: "297-879-0308",
    email: "apedlowl@fda.gov",
    package: null,
    wallet_balance: 11,
  },
  {
    id: 23,
    name: "Raphaela Arkill",
    phone: "803-830-6852",
    email: "rarkillm@over-blog.com",
    package: null,
    wallet_balance: 909,
  },
  {
    id: 24,
    name: "Giffer Mackerel",
    phone: "948-430-5575",
    email: "gmackereln@storify.com",
    package: null,
    wallet_balance: 72,
  },
  {
    id: 25,
    name: "Steve Petrovykh",
    phone: "433-225-1558",
    email: "spetrovykho@php.net",
    package: null,
    wallet_balance: 479,
  },
  {
    id: 26,
    name: "Valentin Dudlestone",
    phone: "370-821-0538",
    email: "vdudlestonep@photobucket.com",
    package: null,
    wallet_balance: 80,
  },
  {
    id: 27,
    name: "Redd Attryde",
    phone: "390-487-3936",
    email: "rattrydeq@w3.org",
    package: null,
    wallet_balance: 465,
  },
  {
    id: 28,
    name: "Charmain Manson",
    phone: "734-735-3271",
    email: "cmansonr@about.me",
    package: null,
    wallet_balance: 369,
  },
  {
    id: 29,
    name: "Brigit Jouannot",
    phone: "939-839-4458",
    email: "bjouannots@tamu.edu",
    package: null,
    wallet_balance: 215,
  },
  {
    id: 30,
    name: "Joe Pude",
    phone: "336-226-9204",
    email: "jpudet@wunderground.com",
    package: null,
    wallet_balance: 28,
  },
];
export const uploadedFiles = [
  {
    img: "https://i.ibb.co/54pG5yX/b9-FZ9-Bg3c8hjda3prd-Rf-Lv-Bxg-Qlh-So-WGc1s7-Yt82.png",
    name: "product1.png",
    size: "3kb",
  },
  {
    img: "https://i.ibb.co/r0PGwLp/Bja-Okpusnsh0h-Fhfsz-Ax-Pwswl-Ksb7-Un-QOps-X6-JV5.png",
    name: "product2.png",
    size: "7kb",
  },
  {
    img: "https://i.ibb.co/61DH7FP/BNMH61mikpe0q5l5b-QCw-PFour4-KL91-Zthm-IXtd8t.png",
    name: "product3.png",
    size: "19kb",
  },
  {
    img: "https://i.ibb.co/9h4W1pf/CAb2-KLPKmv-J0-X1z-Xi0d-P2l-IVFdglpy199-Yb-A89-Oa.png",
    name: "product4.png",
    size: "5kb",
  },
  {
    img: "https://i.ibb.co/ftf7rM1/dq-YEQK55-VZShibd9-ZTFo2dwh9fp6-Iu848b-Ol-Iu-Ae.png",
    name: "product5.png",
    size: "3kb",
  },
  {
    img: "https://i.ibb.co/PrxNC1L/Pb-O1ctng03a76-O2-Hw-NZe-Xq-OWCRDA7d-VADcxm-L0-We.png",
    name: "product6.png",
    size: "29kb",
  },
  {
    img: "https://i.ibb.co/7p1thFz/R2-NLXc-CSAFv-Vp-Ua-Th3ve4-O4whv8-TU4o3-Kotr-H1g-L.png",
    name: "product7.png",
    size: "4kb",
  },
  {
    img: "https://i.ibb.co/jg8M5JL/TUl-GRHTz-Dt2-VCOYf-Ykov-Zixif1-Ir-Vr-Lbso-SILIMM.png",
    name: "product8.png",
    size: "29kb",
  },
  {
    img: "https://i.ibb.co/Mkw1W6J/yd1l-Kx56-WYc6ji-HRKxq-VG6w-Rcg1-Br-Mpkmnz-Dw-OQN.png",
    name: "product9.png",
    size: "219kb",
  },
  {
    img: "https://i.ibb.co/BKGp6hG/y-Fs-Ko-Cyofrd-X5028g-Ex-MWx-VLv00u-Nzd-Bz-Hw1x-FZe.png",
    name: "product10.png",
    size: "209kb",
  },
];

export const allProducts = [
  {
    id: 1,
    name: "Veal - Sweetbread",
    img: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
    added_by: "Valaria Eley",
    sale_count: 315,
    base_price: 684,
    rating: 6,
    stock: 337,
    todays_deal: false,
    published: true,
    featured: false,
  },
  {
    id: 2,
    name: "Wine - German Riesling",
    img: "http://dummyimage.com/100x100.png/dddddd/000000",
    added_by: "Redd Brockie",
    sale_count: 921,
    base_price: 427,
    rating: 1,
    stock: 389,
    todays_deal: true,
    published: false,
    featured: true,
  },
  {
    id: 3,
    name: "Flour - Whole Wheat",
    img: "http://dummyimage.com/100x100.png/cc0000/ffffff",
    added_by: "Morse Fragino",
    sale_count: 158,
    base_price: 597,
    rating: 6,
    stock: 488,
    todays_deal: true,
    published: false,
    featured: false,
  },
  {
    id: 4,
    name: "Syrup - Chocolate",
    img: "http://dummyimage.com/100x100.png/dddddd/000000",
    added_by: "Jareb Rix",
    sale_count: 282,
    base_price: 607,
    rating: 7,
    stock: 260,
    todays_deal: false,
    published: false,
    featured: false,
  },
  {
    id: 5,
    name: "Oil - Cooking Spray",
    img: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
    added_by: "Veda Delete",
    sale_count: 882,
    base_price: 389,
    rating: 6,
    stock: 124,
    todays_deal: true,
    published: true,
    featured: true,
  },
  {
    id: 6,
    name: "Salt - Seasoned",
    img: "http://dummyimage.com/100x100.png/dddddd/000000",
    added_by: "Marinna Pinnocke",
    sale_count: 320,
    base_price: 116,
    rating: 8,
    stock: 303,
    todays_deal: true,
    published: false,
    featured: false,
  },
  {
    id: 7,
    name: "Coke - Classic, 355 Ml",
    img: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
    added_by: "Haskel Godber",
    sale_count: 885,
    base_price: 271,
    rating: 3,
    stock: 243,
    todays_deal: false,
    published: false,
    featured: true,
  },
  {
    id: 8,
    name: "Soup - Campbells, Beef Barley",
    img: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
    added_by: "Crystie Doche",
    sale_count: 983,
    base_price: 654,
    rating: 3,
    stock: 145,
    todays_deal: false,
    published: false,
    featured: true,
  },
  {
    id: 9,
    name: "Brandy - Orange, Mc Guiness",
    img: "http://dummyimage.com/100x100.png/dddddd/000000",
    added_by: "Renard Beadles",
    sale_count: 851,
    base_price: 418,
    rating: 0,
    stock: 141,
    todays_deal: true,
    published: true,
    featured: false,
  },
  {
    id: 10,
    name: "Muffin Mix - Carrot",
    img: "http://dummyimage.com/100x100.png/ff4444/ffffff",
    added_by: "Melva Sudy",
    sale_count: 258,
    base_price: 258,
    rating: 2,
    stock: 11,
    todays_deal: false,
    published: false,
    featured: false,
  },
  {
    id: 11,
    name: "Sping Loaded Cup Dispenser",
    img: "http://dummyimage.com/100x100.png/cc0000/ffffff",
    added_by: "Jaquenetta Hanfrey",
    sale_count: 761,
    base_price: 623,
    rating: 0,
    stock: 240,
    todays_deal: true,
    published: true,
    featured: true,
  },
  {
    id: 12,
    name: "Cumin - Whole",
    img: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
    added_by: "Rozalie Loseby",
    sale_count: 909,
    base_price: 365,
    rating: 2,
    stock: 170,
    todays_deal: true,
    published: true,
    featured: true,
  },
  {
    id: 13,
    name: "Tomatoes - Diced, Canned",
    img: "http://dummyimage.com/100x100.png/dddddd/000000",
    added_by: "Brana Vedekhin",
    sale_count: 394,
    base_price: 117,
    rating: 7,
    stock: 433,
    todays_deal: true,
    published: true,
    featured: true,
  },
  {
    id: 14,
    name: "Spice - Paprika",
    img: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
    added_by: "Cora Potzold",
    sale_count: 691,
    base_price: 212,
    rating: 1,
    stock: 60,
    todays_deal: false,
    published: true,
    featured: false,
  },
  {
    id: 15,
    name: "Compound - Raspberry",
    img: "http://dummyimage.com/100x100.png/ff4444/ffffff",
    added_by: "Myriam Gribben",
    sale_count: 830,
    base_price: 683,
    rating: 6,
    stock: 425,
    todays_deal: false,
    published: true,
    featured: true,
  },
  {
    id: 16,
    name: "Longos - Chicken Cordon Bleu",
    img: "http://dummyimage.com/100x100.png/ff4444/ffffff",
    added_by: "Borden Phidgin",
    sale_count: 186,
    base_price: 328,
    rating: 10,
    stock: 483,
    todays_deal: true,
    published: false,
    featured: true,
  },
  {
    id: 17,
    name: "Fond - Chocolate",
    img: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
    added_by: "Michele Caldaro",
    sale_count: 563,
    base_price: 631,
    rating: 9,
    stock: 47,
    todays_deal: true,
    published: true,
    featured: false,
  },
  {
    id: 18,
    name: "Sausage - Breakfast",
    img: "http://dummyimage.com/100x100.png/ff4444/ffffff",
    added_by: "Ronna Matsell",
    sale_count: 497,
    base_price: 675,
    rating: 3,
    stock: 269,
    todays_deal: false,
    published: false,
    featured: false,
  },
  {
    id: 19,
    name: "Lamb - Loin Chops",
    img: "http://dummyimage.com/100x100.png/ff4444/ffffff",
    added_by: "Bobbee Gandey",
    sale_count: 532,
    base_price: 399,
    rating: 5,
    stock: 202,
    todays_deal: true,
    published: false,
    featured: false,
  },
  {
    id: 20,
    name: "Steam Pan Full Lid",
    img: "http://dummyimage.com/100x100.png/dddddd/000000",
    added_by: "Theadora Lemmer",
    sale_count: 233,
    base_price: 570,
    rating: 4,
    stock: 457,
    todays_deal: false,
    published: true,
    featured: false,
  },
  {
    id: 21,
    name: "Ice Cream Bar - Rolo Cone",
    img: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
    added_by: "Harley Ducker",
    sale_count: 172,
    base_price: 455,
    rating: 10,
    stock: 108,
    todays_deal: true,
    published: false,
    featured: true,
  },
  {
    id: 22,
    name: "Appetizer - Mushroom Tart",
    img: "http://dummyimage.com/100x100.png/ff4444/ffffff",
    added_by: "Maura Alderson",
    sale_count: 344,
    base_price: 456,
    rating: 0,
    stock: 125,
    todays_deal: false,
    published: true,
    featured: false,
  },
  {
    id: 23,
    name: "Soupcontfoam16oz 116con",
    img: "http://dummyimage.com/100x100.png/ff4444/ffffff",
    added_by: "Mallorie Worman",
    sale_count: 118,
    base_price: 143,
    rating: 5,
    stock: 264,
    todays_deal: false,
    published: true,
    featured: true,
  },
  {
    id: 24,
    name: "Chicken - Whole",
    img: "http://dummyimage.com/100x100.png/dddddd/000000",
    added_by: "Harmony Bengtsson",
    sale_count: 591,
    base_price: 109,
    rating: 7,
    stock: 322,
    todays_deal: true,
    published: false,
    featured: false,
  },
  {
    id: 25,
    name: "Filo Dough",
    img: "http://dummyimage.com/100x100.png/dddddd/000000",
    added_by: "Zorine Alliband",
    sale_count: 980,
    base_price: 294,
    rating: 3,
    stock: 62,
    todays_deal: false,
    published: true,
    featured: true,
  },
  {
    id: 26,
    name: "Carrots - Mini Red Organic",
    img: "http://dummyimage.com/100x100.png/cc0000/ffffff",
    added_by: "Eunice Wareing",
    sale_count: 956,
    base_price: 674,
    rating: 5,
    stock: 497,
    todays_deal: true,
    published: false,
    featured: true,
  },
  {
    id: 27,
    name: "Ice Cream Bar - Hageen Daz To",
    img: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
    added_by: "Caye Candie",
    sale_count: 646,
    base_price: 317,
    rating: 7,
    stock: 364,
    todays_deal: false,
    published: true,
    featured: false,
  },
  {
    id: 28,
    name: "Oven Mitts - 15 Inch",
    img: "http://dummyimage.com/100x100.png/cc0000/ffffff",
    added_by: "Nissy Bazley",
    sale_count: 281,
    base_price: 69,
    rating: 3,
    stock: 210,
    todays_deal: true,
    published: true,
    featured: false,
  },
  {
    id: 29,
    name: "Cheese - Cheddar, Old White",
    img: "http://dummyimage.com/100x100.png/dddddd/000000",
    added_by: "Row Vigus",
    sale_count: 559,
    base_price: 222,
    rating: 0,
    stock: 383,
    todays_deal: false,
    published: false,
    featured: false,
  },
  {
    id: 30,
    name: "Daves Island Stinger",
    img: "http://dummyimage.com/100x100.png/dddddd/000000",
    added_by: "Darelle Binstead",
    sale_count: 612,
    base_price: 441,
    rating: 7,
    stock: 29,
    todays_deal: false,
    published: false,
    featured: true,
  },
  {
    id: 31,
    name: "Wine - Merlot Vina Carmen",
    img: "http://dummyimage.com/100x100.png/cc0000/ffffff",
    added_by: "Edouard Lilion",
    sale_count: 798,
    base_price: 298,
    rating: 1,
    stock: 498,
    todays_deal: false,
    published: true,
    featured: true,
  },
  {
    id: 32,
    name: "French Kiss Vanilla",
    img: "http://dummyimage.com/100x100.png/cc0000/ffffff",
    added_by: "Emmaline Feake",
    sale_count: 173,
    base_price: 268,
    rating: 10,
    stock: 299,
    todays_deal: false,
    published: true,
    featured: false,
  },
  {
    id: 33,
    name: "Juice - Lemon",
    img: "http://dummyimage.com/100x100.png/ff4444/ffffff",
    added_by: "Sanson Durno",
    sale_count: 22,
    base_price: 660,
    rating: 8,
    stock: 414,
    todays_deal: false,
    published: true,
    featured: true,
  },
  {
    id: 34,
    name: "Calypso - Pineapple Passion",
    img: "http://dummyimage.com/100x100.png/cc0000/ffffff",
    added_by: "Kendra MacGlory",
    sale_count: 675,
    base_price: 692,
    rating: 7,
    stock: 393,
    todays_deal: false,
    published: true,
    featured: true,
  },
  {
    id: 35,
    name: "Ice Cream - Vanilla",
    img: "http://dummyimage.com/100x100.png/cc0000/ffffff",
    added_by: "Nariko Tringham",
    sale_count: 184,
    base_price: 453,
    rating: 5,
    stock: 22,
    todays_deal: true,
    published: false,
    featured: false,
  },
  {
    id: 36,
    name: "Pork - Bacon Cooked Slcd",
    img: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
    added_by: "Cordelia Gregoratti",
    sale_count: 682,
    base_price: 658,
    rating: 8,
    stock: 268,
    todays_deal: false,
    published: true,
    featured: false,
  },
  {
    id: 37,
    name: "Flour - Bran, Red",
    img: "http://dummyimage.com/100x100.png/dddddd/000000",
    added_by: "Allyson Stebles",
    sale_count: 793,
    base_price: 276,
    rating: 9,
    stock: 322,
    todays_deal: false,
    published: false,
    featured: false,
  },
  {
    id: 38,
    name: "Bread - Pullman, Sliced",
    img: "http://dummyimage.com/100x100.png/cc0000/ffffff",
    added_by: "Gilles Anetts",
    sale_count: 82,
    base_price: 469,
    rating: 7,
    stock: 129,
    todays_deal: true,
    published: true,
    featured: true,
  },
  {
    id: 39,
    name: "Cheese - Sheep Milk",
    img: "http://dummyimage.com/100x100.png/cc0000/ffffff",
    added_by: "Rianon Bargery",
    sale_count: 840,
    base_price: 71,
    rating: 9,
    stock: 129,
    todays_deal: false,
    published: false,
    featured: true,
  },
  {
    id: 40,
    name: "Lamb - Shoulder, Boneless",
    img: "http://dummyimage.com/100x100.png/cc0000/ffffff",
    added_by: "Gregor Murdie",
    sale_count: 252,
    base_price: 497,
    rating: 6,
    stock: 355,
    todays_deal: false,
    published: true,
    featured: true,
  },
  {
    id: 41,
    name: "Wine - White, Riesling, Henry Of",
    img: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
    added_by: "Evangelin Blondelle",
    sale_count: 923,
    base_price: 81,
    rating: 1,
    stock: 285,
    todays_deal: false,
    published: true,
    featured: false,
  },
  {
    id: 42,
    name: "Bread - White, Unsliced",
    img: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
    added_by: "Riley Rameaux",
    sale_count: 771,
    base_price: 154,
    rating: 9,
    stock: 443,
    todays_deal: false,
    published: false,
    featured: false,
  },
  {
    id: 43,
    name: "Southern Comfort",
    img: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
    added_by: "Josee Northway",
    sale_count: 863,
    base_price: 224,
    rating: 8,
    stock: 319,
    todays_deal: true,
    published: true,
    featured: true,
  },
  {
    id: 44,
    name: "Artichokes - Jerusalem",
    img: "http://dummyimage.com/100x100.png/ff4444/ffffff",
    added_by: "Frasco O'Spellissey",
    sale_count: 581,
    base_price: 142,
    rating: 7,
    stock: 140,
    todays_deal: true,
    published: true,
    featured: true,
  },
  {
    id: 45,
    name: "Chicken - Thigh, Bone In",
    img: "http://dummyimage.com/100x100.png/cc0000/ffffff",
    added_by: "Albrecht Meredith",
    sale_count: 413,
    base_price: 149,
    rating: 10,
    stock: 212,
    todays_deal: false,
    published: true,
    featured: true,
  },
  {
    id: 46,
    name: "Chinese Foods - Pepper Beef",
    img: "http://dummyimage.com/100x100.png/ff4444/ffffff",
    added_by: "Lazarus Chetter",
    sale_count: 97,
    base_price: 220,
    rating: 10,
    stock: 177,
    todays_deal: true,
    published: true,
    featured: true,
  },
  {
    id: 47,
    name: "Ecolab - Mikroklene 4/4 L",
    img: "http://dummyimage.com/100x100.png/dddddd/000000",
    added_by: "Nolie Rippingall",
    sale_count: 965,
    base_price: 537,
    rating: 6,
    stock: 417,
    todays_deal: false,
    published: false,
    featured: false,
  },
  {
    id: 48,
    name: "Beer - Mcauslan Apricot",
    img: "http://dummyimage.com/100x100.png/ff4444/ffffff",
    added_by: "Kristan Witheridge",
    sale_count: 680,
    base_price: 284,
    rating: 8,
    stock: 118,
    todays_deal: false,
    published: false,
    featured: true,
  },
  {
    id: 49,
    name: "Turkey - Breast, Smoked",
    img: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
    added_by: "Aundrea Brasseur",
    sale_count: 391,
    base_price: 539,
    rating: 5,
    stock: 177,
    todays_deal: false,
    published: false,
    featured: false,
  },
  {
    id: 50,
    name: "Pie Filling - Apple",
    img: "http://dummyimage.com/100x100.png/ff4444/ffffff",
    added_by: "Vally Potte",
    sale_count: 37,
    base_price: 319,
    rating: 1,
    stock: 5,
    todays_deal: true,
    published: false,
    featured: false,
  },
];
