on:
  push:
    branches:
      - main
name: Deploy website on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2

      
    - name: React Project
      run: |
        npm install
        npm run build
          
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.markutos.com
        username: nitu@staging.markutos.com
        password: '@O9i6?sBF{*O'
        local-dir: ./build/

